### ISSUE TITLE
Feature Request: ctrl/cmd+p toggle

### ISSUE THREAD

**Issue by greenmanspirit** [deathau/cm-show-whitespace-obsidian#4]
I think it would be useful to allow show whitespace to be toggled through ctrl/cmd+p rather than enabling and disabling the plugin.

**Comment by deathau** [comment]
Good idea 👍 
I already have code elsewhere to achieve this, I think. It shouldn't be too hard

**Comment by greenmanspirit** [comment]
Works perfectly, thanks!
