### ISSUE TITLE
New line character disappears

### ISSUE THREAD

**Issue by NomarCub** [deathau/cm-show-whitespace-obsidian#5]
The last new line character of files disappears after placing the cursor on that line.

Empty last line
![](https://user-images.githubusercontent.com/5298006/99155029-bce49d80-26b4-11eb-8470-7841b37345f2.gif)

Not empty last line
![](https://user-images.githubusercontent.com/5298006/99155040-d0900400-26b4-11eb-867b-e70d5734bd48.gif)

**Comment by deathau** [comment]
That last new line shouldn't appear at all (because you don't have a new line there).

I've found why it appears at first, and have a fix to hide it altogether.
